version: "3.9"

services:
  api:
    container_name: api
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app

  minio:
    image: minio/minio:RELEASE.2022-06-03T01-40-53Z.fips
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    volumes:
      - .:/app
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 root password;
      /usr/bin/mc mb myminio/videos;
      exit 0;
      "

volumes:
  minio-data:
